services:
  mock-slant-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
    volumes:
      - ./data:/app/data:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 
      start_period: 40s
    networks:
      - slant-network

  # Development service with hot reload
  mock-slant-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - slant-network
    profiles:
      - dev

networks:
  slant-network:
    driver: bridge 